name: Docker build (smoke)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Dockerfile (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false            # только собираем, никуда не публикуем
          tags: local/test:latest
          cache-from: type=gha   # кэш сборки между запусками
          cache-to: type=gha,mode=max
